from collections import OrderedDict
mardek = [("HP", "self.stats['basehp']+self.stats['LVL']*self.stats['hplvl']"),
    ("MP", "self.stats['SPR']*self.stats['LVL']"),
    ("MAXHP", "self.stats['HP']"),
    ("MAXMP", "self.stats['MP']"),
    ("DEF", "0"),
    ("MDEF", "0"),
    ("CRIT", "0"),
    ("POW", "0"),
    ("FireRes", "0"),
    ("WaterRes", "0"),
    ("EarthRes", "0"),
    ("AirRes", "0"),
    ("LightRes", "0"),
    ("DarkRes", "0"),
    ("FigRes", "0"),
    ("AetherRes", "0"),
    ("DevineRes", "0"),
    ("PhysicalRes", "0"),
    ("ThaumaRes", "0"),
    ("EVE", "0")]